// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulation} from '../models';

export function Get_accounting_data(arg1:number,arg2:number,arg3:string):Promise<Array<simulation.FinanceReportEntry>>;

export function Get_financial_report(arg1:number,arg2:number):Promise<simulation.Financial_Report>;

export function Greet(arg1:string):Promise<string>;
