// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get_accounting_data(arg1, arg2, arg3) {
  return window['go']['main']['App']['Get_accounting_data'](arg1, arg2, arg3);
}

export function Get_availible_decisions(arg1) {
  return window['go']['main']['App']['Get_availible_decisions'](arg1);
}

export function Get_bank_balance(arg1) {
  return window['go']['main']['App']['Get_bank_balance'](arg1);
}

export function Get_current_stock(arg1) {
  return window['go']['main']['App']['Get_current_stock'](arg1);
}

export function Get_financial_report(arg1, arg2) {
  return window['go']['main']['App']['Get_financial_report'](arg1, arg2);
}

export function Get_marketing_statistics(arg1, arg2) {
  return window['go']['main']['App']['Get_marketing_statistics'](arg1, arg2);
}

export function Get_past_decisions(arg1, arg2) {
  return window['go']['main']['App']['Get_past_decisions'](arg1, arg2);
}

export function Get_personelle_report(arg1, arg2, arg3) {
  return window['go']['main']['App']['Get_personelle_report'](arg1, arg2, arg3);
}

export function Get_product_statistics(arg1, arg2) {
  return window['go']['main']['App']['Get_product_statistics'](arg1, arg2);
}

export function Get_production_report(arg1, arg2) {
  return window['go']['main']['App']['Get_production_report'](arg1, arg2);
}

export function Get_sales_statistics(arg1, arg2) {
  return window['go']['main']['App']['Get_sales_statistics'](arg1, arg2);
}

export function Get_simulation_step() {
  return window['go']['main']['App']['Get_simulation_step']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Initial_app_load() {
  return window['go']['main']['App']['Initial_app_load']();
}

export function New_simulation() {
  return window['go']['main']['App']['New_simulation']();
}

export function Revert_simulation() {
  return window['go']['main']['App']['Revert_simulation']();
}

export function Submit_decisions(arg1, arg2) {
  return window['go']['main']['App']['Submit_decisions'](arg1, arg2);
}

export function Trigger_simulation(arg1) {
  return window['go']['main']['App']['Trigger_simulation'](arg1);
}
