// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate_product_stats(arg1, arg2, arg3) {
  return window['go']['main']['App']['Calculate_product_stats'](arg1, arg2, arg3);
}

export function Get_company(arg1) {
  return window['go']['main']['App']['Get_company'](arg1);
}

export function Get_decisions(arg1, arg2) {
  return window['go']['main']['App']['Get_decisions'](arg1, arg2);
}

export function Get_external_factors() {
  return window['go']['main']['App']['Get_external_factors']();
}

export function Get_past_decisions(arg1, arg2) {
  return window['go']['main']['App']['Get_past_decisions'](arg1, arg2);
}

export function Get_simulation_step() {
  return window['go']['main']['App']['Get_simulation_step']();
}

export function Get_unemployed(arg1) {
  return window['go']['main']['App']['Get_unemployed'](arg1);
}

export function Initial_app_load() {
  return window['go']['main']['App']['Initial_app_load']();
}

export function New_simulation(arg1) {
  return window['go']['main']['App']['New_simulation'](arg1);
}

export function Revert_simulation() {
  return window['go']['main']['App']['Revert_simulation']();
}

export function Submit_decisions(arg1, arg2) {
  return window['go']['main']['App']['Submit_decisions'](arg1, arg2);
}

export function Temp_generate_new_emloyee(arg1, arg2, arg3) {
  return window['go']['main']['App']['Temp_generate_new_emloyee'](arg1, arg2, arg3);
}

export function Trigger_simulation(arg1) {
  return window['go']['main']['App']['Trigger_simulation'](arg1);
}
