// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulation} from '../models';

export function Calculate_product_stats(arg1:number,arg2:simulation.Decisions_product,arg3:simulation.Decisions_research):Promise<simulation.Product>;

export function Get_company(arg1:number):Promise<simulation.Company>;

export function Get_decisions(arg1:number,arg2:number):Promise<simulation.Decisions>;

export function Get_external_factors():Promise<simulation.External_factors>;

export function Get_past_decisions(arg1:number,arg2:number):Promise<simulation.Decisions>;

export function Get_simulation_step():Promise<number>;

export function Get_unemployed(arg1:simulation.Employee_type):Promise<Array<simulation.Employee>>;

export function Initial_app_load():Promise<void>;

export function New_simulation(arg1:number):Promise<simulation.External_factors>;

export function Revert_simulation():Promise<number>;

export function Submit_decisions(arg1:number,arg2:simulation.Decisions):Promise<void>;

export function Temp_generate_new_emloyee(arg1:number,arg2:number,arg3:simulation.Employee_type):Promise<number>;

export function Trigger_simulation(arg1:boolean):Promise<simulation.External_factors>;
